### ISSUE TITLE
Move assets over to something more cloudish

### ISSUE THREAD

**Issue by pjf** [pjf/rickastley#3]
Right now all our music files are served from Dropbox, which isn't particularly fast, and may be responsible for some of the delays we've seen when first connecting. We should serve them from something more cloudish, like S3 or cloudfront.

**Comment by lf-** [comment]
This is fixed by the latest commit. You should close it ;-)

**Comment by pjf** [comment]
@lf- : Oh gosh, you're right! Thank you!

Closed in ee3bb566913a8faf18501acf29239c31e4ba6f80.
